this.EXPORTED_SYMBOLS = [ "peer_name_map_list" ];

this.peer_name_map_list = {
	'7T' : 'aTorrent for Android',
	'AB' : 'AnyEvent::BitTorrent',
	'AG' : 'Ares',
	'A~' : 'Ares',
	'AR' : 'Arctic',
	'AV' : 'Avicora',
	'AT' : 'Artemis',
	'AX' : 'BitPump',
	'AZ' : 'Azureus',
	'BB' : 'BitBuddy',
	'BC' : 'BitComet',
	'BF' : 'Bitflu',
	'BG' : 'BTG',
	'BL' : 'BitBlinder',
	'BP' : 'BitTorrent Pro',
	'BR' : 'BitRocket',
	'BS' : 'BTSlave',
	'BT' : 'BBtor',
	'BW' : 'BitWombat',
	'BX' : '~Bittorrent X',
	'CD' : 'Enhanced CTorrent',
	'CT' : 'CTorrent',
	'DE' : 'DelugeTorrent',
	'DP' : 'Propagate Data Client',
	'EB' : 'EBit',
	'ES' : 'electric sheep',
	'FC' : 'FileCroc',
	'FT' : 'FoxTorrent',
	'FX' : 'Freebox BitTorrent',
	'GS' : 'GSTorrent',
	'HK' : 'Hekate',
	'HL' : 'Halite',
	'HM' : 'hMule',
	'HN' : 'Hydranode',
	'IL' : 'iLivid',
	'JS' : 'Justseed.it client',
	'JT' : 'JavaTorrent',
	'KG' : 'KGet',
	'KT' : 'KTorrent',
	'LC' : 'LeechCraft',
	'LH' : 'LH-ABC',
	'LP' : 'Lphant',
	'LT' : 'libtorrent',
	'lt' : 'libTorrent',
	'LW' : 'LimeWire',
	'MK' : 'Meerkat',
	'MO' : 'MonoTorrent',
	'MP' : 'MooPolice',
	'MR' : 'Miro',
	'MT' : 'MoonlightTorrent',
	'NB' : 'Net::BitTorrent',
	'NX' : 'Net Transport',
	'OS' : 'OneSwarm',
	'OT' : 'OmegaTorrent',
	'PB' : 'Protocol::BitTorrent',
	'PD' : 'Pando',
	'PT' : 'PHPTracker',
	'qB' : 'qBittorrent',
	'QD' : 'QQDownload',
	'QT' : 'Qt 4 Torrent example',
	'RT' : 'Retriever',
	'RZ' : 'RezTorrent',
	'S~' : 'Shareaza alpha/beta',
	'SB' : '~Swiftbit',
	'SD' : 'Thunder',
	'SM' : 'SoMud',
	'SP' : 'BitSpirit',
	'SS' : 'SwarmScope',
	'ST' : 'SymTorrent',
	'st' : 'sharktorrent',
	'SZ' : 'Shareaza',
	'TE' : 'terasaur Seed Bank',
	'TL' : 'Tribler',
	'TN' : 'TorrentDotNET',
	'TR' : 'Transmission',
	'TS' : 'Torrentstorm',
	'TT' : 'TuoTu',
	'UL' : 'uLeecher!',
	'UM' : 'mTorrent for Mac',
	'UT' : 'mTorrent',
	'VG' : 'Vagaa',
	'WT' : 'BitLet',
	'WY' : 'FireTorrent',
	'XL' : 'Xunlei',
	'XS' : 'XSwifter',
	'XT' : 'XanTorrent',
	'XX' : 'Xtorrent',
	'ZT' : 'ZipTorrent'
};
